/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AparenciaRouteImport } from './routes/aparencia'
import { Route as ArranqueRouteImport } from './routes/arranque'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as DefinicoesRouteImport } from './routes/definicoes'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as UtilizadoresRouteImport } from './routes/utilizadores'
import { Route as EcrasIndexRouteImport } from './routes/ecras.index'
import { Route as EcrasIdRouteImport } from './routes/ecras.$id'
import { Route as LayoutsIndexRouteImport } from './routes/layouts.index'
import { Route as LayoutsIdRouteImport } from './routes/layouts.$id'
import { Route as PlayerTokenRouteImport } from './routes/player.$token'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as PreviewLayoutIdRouteImport } from './routes/preview.layout.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AparenciaRoute = AparenciaRouteImport.update({
  id: '/aparencia',
  path: '/aparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ArranqueRoute = ArranqueRouteImport.update({
  id: '/arranque',
  path: '/arranque',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinicoesRoute = DefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilizadoresRoute = UtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EcrasIndexRoute = EcrasIndexRouteImport.update({
  id: '/ecras/',
  path: '/ecras/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcrasIdRoute = EcrasIdRouteImport.update({
  id: '/ecras/$id',
  path: '/ecras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsIndexRoute = LayoutsIndexRouteImport.update({
  id: '/layouts/',
  path: '/layouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsIdRoute = LayoutsIdRouteImport.update({
  id: '/layouts/$id',
  path: '/layouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerTokenRoute = PlayerTokenRouteImport.update({
  id: '/player/$token',
  path: '/player/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewLayoutIdRoute = PreviewLayoutIdRouteImport.update({
  id: '/preview/layout/$id',
  path: '/preview/layout/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aparencia': typeof AparenciaRoute
  '/arranque': typeof ArranqueRoute
  '/avisos': typeof AvisosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/clientes': typeof ClientesRoute
  '/definicoes': typeof DefinicoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/utilizadores': typeof UtilizadoresRoute
  '/ecras/$id': typeof EcrasIdRoute
  '/layouts/$id': typeof LayoutsIdRoute
  '/player/$token': typeof PlayerTokenRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/ecras/': typeof EcrasIndexRoute
  '/layouts/': typeof LayoutsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/preview/layout/$id': typeof PreviewLayoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aparencia': typeof AparenciaRoute
  '/arranque': typeof ArranqueRoute
  '/avisos': typeof AvisosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/clientes': typeof ClientesRoute
  '/definicoes': typeof DefinicoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/utilizadores': typeof UtilizadoresRoute
  '/ecras/$id': typeof EcrasIdRoute
  '/layouts/$id': typeof LayoutsIdRoute
  '/player/$token': typeof PlayerTokenRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/ecras': typeof EcrasIndexRoute
  '/layouts': typeof LayoutsIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/preview/layout/$id': typeof PreviewLayoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aparencia': typeof AparenciaRoute
  '/arranque': typeof ArranqueRoute
  '/avisos': typeof AvisosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/clientes': typeof ClientesRoute
  '/definicoes': typeof DefinicoesRoute
  '/fontes': typeof FontesRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/utilizadores': typeof UtilizadoresRoute
  '/ecras/$id': typeof EcrasIdRoute
  '/layouts/$id': typeof LayoutsIdRoute
  '/player/$token': typeof PlayerTokenRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/ecras/': typeof EcrasIndexRoute
  '/layouts/': typeof LayoutsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/preview/layout/$id': typeof PreviewLayoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aparencia'
    | '/arranque'
    | '/avisos'
    | '/biblioteca'
    | '/clientes'
    | '/definicoes'
    | '/fontes'
    | '/login'
    | '/relatorios'
    | '/utilizadores'
    | '/ecras/$id'
    | '/layouts/$id'
    | '/player/$token'
    | '/playlists/$id'
    | '/ecras/'
    | '/layouts/'
    | '/playlists/'
    | '/preview/layout/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aparencia'
    | '/arranque'
    | '/avisos'
    | '/biblioteca'
    | '/clientes'
    | '/definicoes'
    | '/fontes'
    | '/login'
    | '/relatorios'
    | '/utilizadores'
    | '/ecras/$id'
    | '/layouts/$id'
    | '/player/$token'
    | '/playlists/$id'
    | '/ecras'
    | '/layouts'
    | '/playlists'
    | '/preview/layout/$id'
  id:
    | '__root__'
    | '/'
    | '/aparencia'
    | '/arranque'
    | '/avisos'
    | '/biblioteca'
    | '/clientes'
    | '/definicoes'
    | '/fontes'
    | '/login'
    | '/relatorios'
    | '/utilizadores'
    | '/ecras/$id'
    | '/layouts/$id'
    | '/player/$token'
    | '/playlists/$id'
    | '/ecras/'
    | '/layouts/'
    | '/playlists/'
    | '/preview/layout/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AparenciaRoute: typeof AparenciaRoute
  ArranqueRoute: typeof ArranqueRoute
  AvisosRoute: typeof AvisosRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ClientesRoute: typeof ClientesRoute
  DefinicoesRoute: typeof DefinicoesRoute
  FontesRoute: typeof FontesRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UtilizadoresRoute: typeof UtilizadoresRoute
  EcrasIdRoute: typeof EcrasIdRoute
  LayoutsIdRoute: typeof LayoutsIdRoute
  PlayerTokenRoute: typeof PlayerTokenRoute
  PlaylistsIdRoute: typeof PlaylistsIdRoute
  EcrasIndexRoute: typeof EcrasIndexRoute
  LayoutsIndexRoute: typeof LayoutsIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  PreviewLayoutIdRoute: typeof PreviewLayoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aparencia': {
      id: '/aparencia'
      path: '/aparencia'
      fullPath: '/aparencia'
      preLoaderRoute: typeof AparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arranque': {
      id: '/arranque'
      path: '/arranque'
      fullPath: '/arranque'
      preLoaderRoute: typeof ArranqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definicoes': {
      id: '/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof DefinicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilizadores': {
      id: '/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof UtilizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecras/': {
      id: '/ecras/'
      path: '/ecras'
      fullPath: '/ecras/'
      preLoaderRoute: typeof EcrasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecras/$id': {
      id: '/ecras/$id'
      path: '/ecras/$id'
      fullPath: '/ecras/$id'
      preLoaderRoute: typeof EcrasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts/': {
      id: '/layouts/'
      path: '/layouts'
      fullPath: '/layouts/'
      preLoaderRoute: typeof LayoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts/$id': {
      id: '/layouts/$id'
      path: '/layouts/$id'
      fullPath: '/layouts/$id'
      preLoaderRoute: typeof LayoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$token': {
      id: '/player/$token'
      path: '/player/$token'
      fullPath: '/player/$token'
      preLoaderRoute: typeof PlayerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/layout/$id': {
      id: '/preview/layout/$id'
      path: '/preview/layout/$id'
      fullPath: '/preview/layout/$id'
      preLoaderRoute: typeof PreviewLayoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AparenciaRoute: AparenciaRoute,
  ArranqueRoute: ArranqueRoute,
  AvisosRoute: AvisosRoute,
  BibliotecaRoute: BibliotecaRoute,
  ClientesRoute: ClientesRoute,
  DefinicoesRoute: DefinicoesRoute,
  FontesRoute: FontesRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  UtilizadoresRoute: UtilizadoresRoute,
  EcrasIdRoute: EcrasIdRoute,
  LayoutsIdRoute: LayoutsIdRoute,
  PlayerTokenRoute: PlayerTokenRoute,
  PlaylistsIdRoute: PlaylistsIdRoute,
  EcrasIndexRoute: EcrasIndexRoute,
  LayoutsIndexRoute: LayoutsIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  PreviewLayoutIdRoute: PreviewLayoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
