/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AparenciaRouteImport } from './routes/aparencia'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as DefinicoesRouteImport } from './routes/definicoes'
import { Route as EcrasRouteImport } from './routes/ecras'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as LayoutsRouteImport } from './routes/layouts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistoRouteImport } from './routes/registo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AparenciaRoute = AparenciaRouteImport.update({
  id: '/aparencia',
  path: '/aparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinicoesRoute = DefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EcrasRoute = EcrasRouteImport.update({
  id: '/ecras',
  path: '/ecras',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsRoute = LayoutsRouteImport.update({
  id: '/layouts',
  path: '/layouts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aparencia': typeof AparenciaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/definicoes': typeof DefinicoesRoute
  '/ecras': typeof EcrasRoute
  '/fontes': typeof FontesRoute
  '/layouts': typeof LayoutsRoute
  '/login': typeof LoginRoute
  '/registo': typeof RegistoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aparencia': typeof AparenciaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/definicoes': typeof DefinicoesRoute
  '/ecras': typeof EcrasRoute
  '/fontes': typeof FontesRoute
  '/layouts': typeof LayoutsRoute
  '/login': typeof LoginRoute
  '/registo': typeof RegistoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aparencia': typeof AparenciaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/definicoes': typeof DefinicoesRoute
  '/ecras': typeof EcrasRoute
  '/fontes': typeof FontesRoute
  '/layouts': typeof LayoutsRoute
  '/login': typeof LoginRoute
  '/registo': typeof RegistoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aparencia'
    | '/biblioteca'
    | '/definicoes'
    | '/ecras'
    | '/fontes'
    | '/layouts'
    | '/login'
    | '/registo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aparencia'
    | '/biblioteca'
    | '/definicoes'
    | '/ecras'
    | '/fontes'
    | '/layouts'
    | '/login'
    | '/registo'
  id:
    | '__root__'
    | '/'
    | '/aparencia'
    | '/biblioteca'
    | '/definicoes'
    | '/ecras'
    | '/fontes'
    | '/layouts'
    | '/login'
    | '/registo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AparenciaRoute: typeof AparenciaRoute
  BibliotecaRoute: typeof BibliotecaRoute
  DefinicoesRoute: typeof DefinicoesRoute
  EcrasRoute: typeof EcrasRoute
  FontesRoute: typeof FontesRoute
  LayoutsRoute: typeof LayoutsRoute
  LoginRoute: typeof LoginRoute
  RegistoRoute: typeof RegistoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aparencia': {
      id: '/aparencia'
      path: '/aparencia'
      fullPath: '/aparencia'
      preLoaderRoute: typeof AparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definicoes': {
      id: '/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof DefinicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecras': {
      id: '/ecras'
      path: '/ecras'
      fullPath: '/ecras'
      preLoaderRoute: typeof EcrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layouts': {
      id: '/layouts'
      path: '/layouts'
      fullPath: '/layouts'
      preLoaderRoute: typeof LayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AparenciaRoute: AparenciaRoute,
  BibliotecaRoute: BibliotecaRoute,
  DefinicoesRoute: DefinicoesRoute,
  EcrasRoute: EcrasRoute,
  FontesRoute: FontesRoute,
  LayoutsRoute: LayoutsRoute,
  LoginRoute: LoginRoute,
  RegistoRoute: RegistoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
